//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace estadisticas_avima.avima
{

    public partial class Avima_PurchaseLine : XPLiteObject
    {
        string fDescription;
        [Size(255)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        string fDocumentNo_;
        [Size(255)]
        [Persistent(@"Document No_")]
        public string DocumentNo_
        {
            get { return fDocumentNo_; }
            set { SetPropertyValue<string>("DocumentNo_", ref fDocumentNo_, value); }
        }
        DateTime fExpectedReceiptDate;
        [Persistent(@"Expected Receipt Date")]
        public DateTime ExpectedReceiptDate
        {
            get { return fExpectedReceiptDate; }
            set { SetPropertyValue<DateTime>("ExpectedReceiptDate", ref fExpectedReceiptDate, value); }
        }
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fItemCategoryCode;
        [Size(255)]
        [Persistent(@"Item Category Code")]
        public string ItemCategoryCode
        {
            get { return fItemCategoryCode; }
            set { SetPropertyValue<string>("ItemCategoryCode", ref fItemCategoryCode, value); }
        }
        string fName;
        [Size(255)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fNo_;
        [Size(255)]
        public string No_
        {
            get { return fNo_; }
            set { SetPropertyValue<string>("No_", ref fNo_, value); }
        }
        double fProductGroupCode;
        [Persistent(@"Product Group Code")]
        public double ProductGroupCode
        {
            get { return fProductGroupCode; }
            set { SetPropertyValue<double>("ProductGroupCode", ref fProductGroupCode, value); }
        }
        double fQuantity;
        public double Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<double>("Quantity", ref fQuantity, value); }
        }
        double fUnitCost;
        [Persistent(@"Unit Cost")]
        public double UnitCost
        {
            get { return fUnitCost; }
            set { SetPropertyValue<double>("UnitCost", ref fUnitCost, value); }
        }
    }

}
